In [1]:
import datetime as d
f = open("input.txt", "r")
s1 = f.readline()
s2 = f.readline()
f.close()

In [2]:
print(len(s1), len(s2))

1001 1000

In [3]:
def editDistance(word1, word2, i, j):
    if not word1 and not word2: 
        return 0
    if len(word1) == i:
        return len(word2) - j
    if len(word2) == j:
        return len(word1) - i
    if word1[i] == word2[j]:
        return editDistance(word1, word2, i+1, j+1)
    insert = editDistance(word1, word2, i, j+1)
    delete = editDistance(word1, word2, i+1, j)
    replace = editDistance(word1, word2, i+1, j+1)
    return min(insert, replace, delete) + 1

In [343]:
a = "AAGGT"
b = "AACAGTTA"
st = d.datetime.now()
print(editDistance(a, b, 0, 0))
print((d.datetime.now()-st).total_seconds())

4
0.005967

In [148]:
def editDistanceTopDown(word1, word2, i, j, dp):
    tmp = 0;
    if not word1 and not word2: 
        return 0
    if len(word1) == i:
        return len(word2) - j
    if len(word2) == j:
        return len(word1) - i
    if dp[i][j] > 0:
        return dp[i][j]
    if word1[i] == word2[j]:
        tmp = editDistanceTopDown(word1, word2, i+1, j+1, dp)
    else:
        insert = editDistanceTopDown(word1, word2, i, j+1, dp)
        delete = editDistanceTopDown(word1, word2, i+1, j, dp)
        replace = editDistanceTopDown(word1, word2, i+1, j+1, dp)
        tmp = min(insert, replace, delete) + 1
    dp[i][j] = tmp
    return tmp

In [149]:
st = d.datetime.now()
dp = [[0 for x in range(len(b)+1)] for y in range(len(a)+1)] 
print(editDistanceTopDown(a, b, 0, 0, dp))
print((d.datetime.now()-st).total_seconds())

9
0.001068

In [150]:
def editDistanceBottomUp(word1, word2):

    m = len(word1)
    n = len(word2)
    dp = [[0 for x in range(n+1)] for y in range(m+1)] 
    for i in range(1, m+1):
        dp[i][0] = i;
    for j in range(1, n+1):
        dp[0][j] = j;
    for i in range(1, m+1):
        for j in range(1, n+1):
            if word1[i-1] == word2[j-1]:
                dp[i][j] = dp[i-1][j-1];
            else:
                dp[i][j] = min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]) + 1
    return dp[m][n]

In [151]:
st = d.datetime.now()
print(editDistanceBottomUp(a,b))
print((d.datetime.now()-st).total_seconds())

9
0.000583

In [201]:
import random, string

xlen = 15
ylen = 15
timeForRecursive = [[0 for j in range(ylen)] for i in range(xlen)]
timeForTopDown = [[0 for j in range(ylen)] for i in range(xlen)]
timeForBottomUp = [[0 for j in range(ylen)] for i in range(xlen)]
for x in range(1, xlen):
    for y in range(1, ylen):
#         s1 = 'a'*x
#         s2 = 'b'*y
#         s1 = ''.join(random.choice(string.ascii_lowercase) for _ in range(x))
#         s2 = ''.join(random.choice(string.ascii_lowercase) for _ in range(y))
        s1 = ''.join(random.choice('ATCG') for _ in range(x))
        s2 = ''.join(random.choice('ATCG') for _ in range(y))
        print(s1,s2)
        st = d.datetime.now()
        ans1 = editDistance(s1, s2, 0, 0)
#         print(editDistance(s1, s2, 0, 0))
        timeForRecursive[x][y] = (d.datetime.now()-st).total_seconds()
        dp = [[0 for x in range(len(s2)+1)] for y in range(len(s1)+1)] 
        st2 = d.datetime.now()
        ans2 = editDistanceTopDown(s1, s2, 0, 0, dp)
        timeForTopDown[x][y] = (d.datetime.now()-st2).total_seconds()
        st3 = d.datetime.now()
        ans3 = editDistanceBottomUp(s1, s2)
        timeForBottomUp[x][y] = (d.datetime.now()-st3).total_seconds()
        if ans1 != ans2 or ans1 != ans3 or ans2 != ans3:
            raise Exception('BUG, ANS NOT EQUAL')
print(timeForRecursive)
print(timeForTopDown)
print(timeForBottomUp)

G C
T TT
T AGA
T TGGG
G ATTGA
A TACTGC
A ATTAGAG
G GTTAGCTC
G CCCGGAAAG
T TGATACGTTT
A AGTCCACTGTA
A AAATGAATGGTA
T AAAGATCTTCAGT
C TGATTGGATGAGCC
AC A
CG CA
TG GCT
CG ACCC
TC TGCCG
TG TCGGTC
GT TCGAGCT
CC TTAATATC
TT CGATATGGA
TT ACTTGAATCA
GT CACTAGGAAGC
TG TGTGATCTAAAT
TA CCTCGCCTTTTGC
AC GGGTTTCCTGGTGC
GTA T
GCT TG
GGA CCA
GTC AGGC
TAC CGGGT
AGA AATAGC
GGA CGTAGAT
TGG ATTTAGAG
AGG TAGTAGAGC
TTC TTTGCACTCC
ACC AGTCGTCAGGC
AGA GTAGTATGCCCT
ATG AATGATAGCCCAG
GTC TTGGTAGTAGACTC
GGGC C
AAGG CC
AGCT AGA
ACGC AGTT
AGCC AAACC
CATT GAATAA
TATC ATATGTG
TGCC AGGTGGTG
GCAG GCCTGCAGG
ATAT ATACGAGAAC
GCGC CGATCGAACGA
ACAC ACCGGGAGACTT
ATCA TTCGGAGTGAGGC
CCAT GGTCAGAGAGCGAC
ATTGG T
AAGTA AG
GCTAC TAT
AGGCT TAAC
TAGGG TGATA
AGACC CATCTG
TTAGA GCCGTAT
CAGGG TAAAGCGA
CAGCA CGGTTACCT
GCCGG ATTCCCTAAC
CGTCA CCCCATAATCT
ATACT AAAGAATTAGCC
CTAGA CCTGCCCTGTGAC
TGGCC TCTCTATAGAACAA
GATATT C
GAACGC GG
CGTACT TTG
TTGTGA GTAT
AAGCCC GCAAT
AGCGGG TATAAC
TGTGAG CGCCCAT
TGAATC GCTGAAAA
CTGAAG GGTGACCGG
CTGTCT CGTCGGAACA
CAGAGG GTAAACAATTA
GCTATT TCAACTGGAACG
TCTTAG GTACAAGCGTGAC
CAAGGT CCATGGAAGACAAC
GCACGTC T
ACCACTC TC
CCCATTG CTG
GCAATAT CACC
GCAGGTA GCGTT
TACAGTC GCTACT
CTGCTGG GTTCAAA
AAGTCGC CGGTAGCT
CCAAGAT TGTAAAATT
CGTTTAT CCGCCAAAGT
CCAGGCT CCATAGGGTTA
GTCATAA TCTAAAGAATCG
CAGATCT AGCGCCTACATTG
GTTGAAT CGTGCAAGTGCCGA
ACAGCTCC T
CATTGGTT AA
TCAGAATT TGG
AAACTGAA AAAG
CCTGGGAT TCAGT
ATGAGAGA GCCTGT
GTGGATAA TTCTCTG
ATCATAAG TAATAAGT
CCGTACGT ATCAAAACC
TATCATAG TCATGTAGTC
AACAAAGT GTAACACCACT
CAGTGTAG GTTGAGTACATC
CTCGAACG AAACCCGCAAAAA
CGACGGAT GCATCTACAAGTTG
CGTACAACC A
TAGCATCAT CA
AGGGCCGTG CCG
CGACGCATC TAGT
CATGGTCAC TCGTC
CAGTCGGGC AGCCGA
TATCGGGTG CGGCTTC
CCTGGGAGG GATACACG
GGTGTAAGG GTCATTAAG
GCGCTCACG GAGATAACAT
TCAGCTCAT GGGGCTTGGAG
TGCTTCTAT AAAATCCTGGGG
TTCCGAATC CCTCCTAATACGT
ACAGCGGTT CAACCACACTTGAT
GCATAGGTCA C
GAGTGCACGC GC
AGGTACACTC TTA
CGACCGGGAT CGGT
AAGTCGAATC GAATG
CATGAAAACT AACATG
GTCTACAAAA AATGTGC
ACTTCTTACC TGTAAGAG
TGATAAATGC AGAGGGAAA
CACGCCAGCC GGAAACGGCC
GTATATATAT GTGAGGTATCC
GTTTTGTTGA GGATCTGTCCCT
GACTGAAGCT TTGATACGTAGGA
TGTGCGTCGA CCCATGGTAAAGAG
ACGATTCCCGA T
GTAGCCCGGCA TA
GTCAGCCATCT CCA
TATTTGTCTCA GACG
ACAGGCCCCGG CTTCC
CAATCCCCTTT GAACGG
AGAGGCTATGA AGAATAA
GTAAGTGTGGG ACCTTTAC
GAACTAAGAAA ATTCAAACC
CTCCTAATTTC GAGGGCGAAT
CTCTAGGCTTC CAAGTGTTTCA
CAATCACCTCT TGCGATACCTTT
TACGTCGCGCT GGGCCCAAAAAGT
ATAACTCCGGC GTCCAAATTTACAT
GACGGTTGAGCT T
GAAGACTAGCTA AA
CTATCGCACAAG TCT
GAGGCGTAAAGT CTCC
CACGGACTTAGG GGATC
GTTCTGCGCATC GCTACT
TAGATAGGAAAA TAGTTGT
CTGAGGTAAAAA GTGTCTCG
CTGCCAAAGTGG CTTTAAACG
CTTTAAGTCGAA GCGCATCTCT
ACCTTTTAACGA GTTATCTCCAC
CGGTGCGGTTAG AATCCCGGAAAA
GTTACCATGTGA CTGCACAGGTTGT
GCCGCATTCACC ATATTCGTCATGTA
TTCCTGAAGCTAC A
TGTTTTAAGTGAT GG
ACGGACCACGGAT AAA
TACGGCTAAGGTC CAGC
GTCAACGACGACC ATGTT
CCAATGCAGAGAT CGTTTG
TTGAGATTGCCAC GGCACGA
CGTCGGGGTGGCT TTGGATGA
TATTTATGTAATA AGTAAGAGG
ACTGGAGACGCGC GGGGGTAACG
GGATACTGCCTGG CGTACGGAGGT
CCAAGCCCTAGCA CTAGTTTTTGAT
GCACCCTAACTCT CCGGCAATCTTCT
TGTCTCATGTGTA ATACGACAGATTCA
CGCCTACTTCCAAC G
AGGTTACTAACACA AC
CAGTCGCTGCATAG GTC
GACTGTATCGAACA AATG
GTACTTGCGACGAG TCACG
GACTTAACACTCGC TCCTCA
CCCTTTAAGAATAC GAATGAC
GCGTACGAGCTGCC TTTCGGAT
AGGAGGCAGTAAAA AAAGGTGCT
GCTTCCGCATGACG GATTAGGGAT
GTCGCCCTGGATGT ACCCTCGAATA
TTCACGCGAGTAAG GCTTAACTACAT
GGGCACGCTTATTT CGTCGCGGGGCTT
CCTGCGGAATCCTA AGCCAACTATCATG
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1.3e-05, 5e-06, 1e-05, 5e-06, 1e-05, 7e-06, 5e-06, 5e-06, 1.1e-05, 5e-06, 5e-06, 7e-06, 1.4e-05, 3.7e-05], [0, 6e-06, 8e-06, 3.1e-05, 2.2e-05, 7e-06, 9e-06, 3.7e-05, 9.5e-05, 2.8e-05, 1.7e-05, 6.7e-05, 6e-06, 9.5e-05, 0.000266], [0, 6e-06, 1.6e-05, 7.8e-05, 0.0001, 0.000328, 2.3e-05, 3.1e-05, 0.000117, 5.5e-05, 1.3e-05, 3.7e-05, 7.5e-05, 1.3e-05, 0.000163], [0, 9e-06, 7e-05, 4.4e-05, 7.9e-05, 7.4e-05, 0.000508, 0.00011, 0.00121, 5.4e-05, 3.8e-05, 0.000339, 0.000271, 0.005069, 0.001821], [0, 3.9e-05, 1e-05, 6.8e-05, 0.000288, 0.000268, 0.001018, 0.002833, 0.001051, 0.00058, 0.016035, 0.001176, 0.001024, 0.001424, 0.007871], [0, 1.6e-05, 1.2e-05, 7.6e-05, 0.000108, 0.001137, 0.004518, 0.004956, 0.004394, 0.003938, 0.00157, 0.018677, 0.03619, 0.019223, 0.000895], [0, 1.3e-05, 2.5e-05, 4.8e-05, 0.000239, 5.2e-05, 0.001619, 0.004694, 0.006761, 0.008498, 0.01183, 0.000449, 0.032107, 0.036794, 0.022057], [0, 1.6e-05, 2.1e-05, 2.9e-05, 1.4e-05, 0.000539, 0.012793, 0.013479, 0.003504, 0.038346, 0.005774, 0.026025, 0.06273, 0.355896, 0.098219], [0, 9e-06, 2.1e-05, 9.9e-05, 0.0007, 0.001015, 0.002791, 0.029135, 0.075916, 0.031674, 0.045773, 0.576912, 0.680129, 0.072711, 0.134983], [0, 1.2e-05, 1.5e-05, 0.000177, 9e-05, 0.002211, 0.005892, 0.097244, 0.200917, 0.109272, 0.109398, 0.008641, 0.055413, 1.866199, 3.233182], [0, 1.2e-05, 1.1e-05, 6.7e-05, 0.002326, 0.003117, 0.021517, 0.000411, 0.292769, 0.097231, 6.300145, 0.287933, 0.76527, 12.592327, 13.424234], [0, 1.3e-05, 1.5e-05, 7.5e-05, 0.003357, 0.003506, 0.00107, 0.000363, 0.181719, 0.018656, 2.105304, 0.703027, 6.244182, 1.296332, 32.61072], [0, 2.3e-05, 1.9e-05, 3.1e-05, 0.000711, 0.022767, 0.005392, 0.0654, 0.071734, 0.230189, 0.25296, 1.135139, 3.586019, 0.909083, 14.193764], [0, 9e-06, 1.7e-05, 0.000163, 0.000153, 0.001006, 0.010363, 0.117447, 0.2124, 0.070745, 0.425923, 1.523753, 14.734218, 5.397983, 57.905356]]
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 5e-06, 3e-06, 8e-06, 3e-06, 7e-06, 5e-06, 2e-06, 2e-06, 9e-06, 3e-06, 3e-06, 3e-06, 1.1e-05, 3.7e-05], [0, 4e-06, 8e-06, 1.9e-05, 1.2e-05, 5e-06, 6e-06, 1.7e-05, 3e-05, 1.7e-05, 1.2e-05, 3e-05, 3e-06, 2.8e-05, 5.7e-05], [0, 5e-06, 1.2e-05, 6e-05, 4.2e-05, 5e-05, 1.6e-05, 2e-05, 2.7e-05, 2.9e-05, 1.3e-05, 2.7e-05, 2.1e-05, 1e-05, 3.3e-05], [0, 1.3e-05, 3.7e-05, 1.6e-05, 3.3e-05, 4.2e-05, 7.6e-05, 4.4e-05, 9.5e-05, 3.8e-05, 3.2e-05, 9.7e-05, 4.9e-05, 7.1e-05, 8.7e-05], [0, 8e-06, 6e-06, 2.5e-05, 3.6e-05, 8.4e-05, 5.2e-05, 0.00013, 7.3e-05, 5e-05, 0.000235, 7.4e-05, 5.5e-05, 6.4e-05, 8.3e-05], [0, 1.4e-05, 9e-06, 2.6e-05, 2.6e-05, 3.8e-05, 6.1e-05, 7.7e-05, 5e-05, 8e-05, 4.7e-05, 9.5e-05, 0.00011, 0.000103, 7e-05], [0, 1.2e-05, 2.2e-05, 1.9e-05, 3.3e-05, 2e-05, 5.6e-05, 6.9e-05, 8.3e-05, 0.000105, 8.9e-05, 4e-05, 0.0001, 0.00015, 0.000109], [0, 1.2e-05, 1.9e-05, 2.1e-05, 1e-05, 5.3e-05, 7.9e-05, 8.4e-05, 6.5e-05, 0.000105, 6.7e-05, 9.4e-05, 0.000132, 0.000144, 0.000141], [0, 9e-06, 1.6e-05, 2.8e-05, 6.1e-05, 5.7e-05, 5.3e-05, 8.4e-05, 0.000116, 0.000155, 0.00012, 0.000154, 0.000169, 0.000136, 0.000151], [0, 6e-06, 1.4e-05, 0.000108, 2.9e-05, 5.4e-05, 6.5e-05, 0.000102, 0.000125, 0.000135, 0.000141, 9.7e-05, 0.000124, 0.000149, 0.00018], [0, 1.1e-05, 1e-05, 2.9e-05, 7e-05, 8.6e-05, 0.000114, 4.8e-05, 0.000203, 0.000132, 0.000189, 0.000151, 0.000163, 0.000217, 0.00024], [0, 1.2e-05, 9e-06, 3e-05, 6.5e-05, 7e-05, 5.4e-05, 5.4e-05, 0.000135, 0.000113, 0.000163, 0.000187, 0.000217, 0.000229, 0.000237], [0, 1.5e-05, 2e-05, 2e-05, 5.6e-05, 0.000197, 9.3e-05, 0.000116, 0.000135, 0.000134, 0.000163, 0.000184, 0.000217, 0.000203, 0.000261], [0, 6e-06, 1.6e-05, 2.8e-05, 4.3e-05, 6.3e-05, 9.7e-05, 0.000142, 0.000183, 0.000124, 0.000183, 0.000289, 0.000203, 0.000247, 0.000264]]
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1e-05, 7e-06, 9e-06, 9e-06, 1.1e-05, 1e-05, 1.1e-05, 0.000154, 1.3e-05, 1.2e-05, 1.4e-05, 1.5e-05, 1.5e-05, 3.3e-05], [0, 1.4e-05, 1.9e-05, 1.9e-05, 1.3e-05, 1.4e-05, 1.5e-05, 1.7e-05, 2e-05, 2e-05, 2.1e-05, 2.3e-05, 2.3e-05, 2.6e-05, 3.3e-05], [0, 1.1e-05, 1.3e-05, 3.5e-05, 3.8e-05, 3.8e-05, 2.1e-05, 2.3e-05, 2.5e-05, 5e-05, 5e-05, 6.1e-05, 3.9e-05, 3.8e-05, 4e-05], [0, 2.3e-05, 3.6e-05, 3.9e-05, 4.3e-05, 5.7e-05, 5.4e-05, 6.4e-05, 7.9e-05, 6.7e-05, 7.2e-05, 8.4e-05, 9e-05, 5.2e-05, 6e-05], [0, 1.9e-05, 1.9e-05, 2.4e-05, 3.5e-05, 6.8e-05, 3.8e-05, 7.3e-05, 5.4e-05, 4.5e-05, 8.5e-05, 5.5e-05, 5.2e-05, 5.5e-05, 6.3e-05], [0, 1.8e-05, 1.9e-05, 2.4e-05, 2.7e-05, 3.2e-05, 3.9e-05, 6.5e-05, 4.5e-05, 5.1e-05, 5.3e-05, 7.2e-05, 6.3e-05, 7.1e-05, 7e-05], [0, 1.9e-05, 2.2e-05, 2.7e-05, 3.1e-05, 3.6e-05, 4.1e-05, 4.7e-05, 5.3e-05, 5.8e-05, 6.8e-05, 6.6e-05, 7.2e-05, 9.1e-05, 8.3e-05], [0, 2.2e-05, 2.6e-05, 3.2e-05, 3.3e-05, 4.1e-05, 5e-05, 5.6e-05, 5.6e-05, 6.5e-05, 6.7e-05, 7.2e-05, 8.1e-05, 8.6e-05, 9.2e-05], [0, 2.2e-05, 2.7e-05, 3.1e-05, 4e-05, 4.4e-05, 4.9e-05, 6e-05, 9.8e-05, 0.000162, 8.5e-05, 9e-05, 9.2e-05, 9.4e-05, 0.000106], [0, 2.8e-05, 3.4e-05, 5.6e-05, 5.3e-05, 5.4e-05, 5.8e-05, 6.6e-05, 7.6e-05, 8.2e-05, 8.3e-05, 9.6e-05, 9.7e-05, 0.000105, 0.000113], [0, 2.6e-05, 3.3e-05, 3.8e-05, 4.9e-05, 6e-05, 6.7e-05, 6.5e-05, 0.00015, 8.3e-05, 9.9e-05, 0.000107, 0.000106, 0.000116, 0.000122], [0, 2.7e-05, 3.3e-05, 4.2e-05, 5.3e-05, 7.4e-05, 6.4e-05, 7.3e-05, 8.8e-05, 9.2e-05, 0.000102, 0.000107, 0.000121, 0.000127, 0.000241], [0, 3e-05, 3.6e-05, 4.3e-05, 5.3e-05, 9.8e-05, 7.5e-05, 8.2e-05, 9.1e-05, 9.9e-05, 0.000109, 0.000117, 0.000133, 0.000132, 0.000147], [0, 3.4e-05, 6.4e-05, 7.1e-05, 6e-05, 6.6e-05, 8.6e-05, 8.8e-05, 0.000109, 0.000104, 0.000117, 0.00015, 0.000135, 0.000161, 0.000152]]

In [202]:
import numpy
a = numpy.asarray(timeForRecursive)
b = numpy.asarray(timeForTopDown)
c = numpy.asarray(timeForBottomUp)

numpy.savetxt("Recursive.csv", a, delimiter=",")
numpy.savetxt("TopDown.csv", b, delimiter=",")
numpy.savetxt("BottomUp.csv", c, delimiter=",")

In [207]:
s1 = 'a'*2000
s2 = 'b'*2000
st3 = d.datetime.now()
print(editDistanceBottomUp(s1, s2))
print((d.datetime.now()-st3).total_seconds())

2000
3.897942

In [234]:
import pandas as pd
# a.index = numpy.arange(1, len(a))


# numpy.savetxt("test.csv", a, delimiter=",")
# df = pd.read_csv('test.csv', header=None)
df_1 = pd.DataFrame(a, columns=range(1,16))
df_1.index += 1
df_1
df_1.to_csv("df.csv", sep=',', encoding='utf-8')

In [223]:
dataset = df
dataset.index += 1

In [224]:
dataset

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.0,0.000013,0.000005,0.000010,0.000005,0.000010,0.000007,0.000005,0.000005,0.000011,0.000005,0.000005,0.000007,0.000014,0.000037
3,0.0,0.000006,0.000008,0.000031,0.000022,0.000007,0.000009,0.000037,0.000095,0.000028,0.000017,0.000067,0.000006,0.000095,0.000266
4,0.0,0.000006,0.000016,0.000078,0.000100,0.000328,0.000023,0.000031,0.000117,0.000055,0.000013,0.000037,0.000075,0.000013,0.000163
5,0.0,0.000009,0.000070,0.000044,0.000079,0.000074,0.000508,0.000110,0.001210,0.000054,0.000038,0.000339,0.000271,0.005069,0.001821
6,0.0,0.000039,0.000010,0.000068,0.000288,0.000268,0.001018,0.002833,0.001051,0.000580,0.016035,0.001176,0.001024,0.001424,0.007871
7,0.0,0.000016,0.000012,0.000076,0.000108,0.001137,0.004518,0.004956,0.004394,0.003938,0.001570,0.018677,0.036190,0.019223,0.000895
8,0.0,0.000013,0.000025,0.000048,0.000239,0.000052,0.001619,0.004694,0.006761,0.008498,0.011830,0.000449,0.032107,0.036794,0.022057
9,0.0,0.000016,0.000021,0.000029,0.000014,0.000539,0.012793,0.013479,0.003504,0.038346,0.005774,0.026025,0.062730,0.355896,0.098219
10,0.0,0.000009,0.000021,0.000099,0.000700,0.001015,0.002791,0.029135,0.075916,0.031674,0.045773,0.576912,0.680129,0.072711,0.134983
11,0.0,0.000012,0.000015,0.000177,0.000090,0.002211,0.005892,0.097244,0.200917,0.109272,0.109398,0.008641,0.055413,1.866199,3.233182
12,0.0,0.000012,0.000011,0.000067,0.002326,0.003117,0.021517,0.000411,0.292769,0.097231,6.300145,0.287933,0.765270,12.592327,13.424234
13,0.0,0.000013,0.000015,0.000075,0.003357,0.003506,0.001070,0.000363,0.181719,0.018656,2.105304,0.703027,6.244182,1.296332,32.610720
14,0.0,0.000023,0.000019,0.000031,0.000711,0.022767,0.005392,0.065400,0.071734,0.230189,0.252960,1.135139,3.586019,0.909083,14.193764
15,0.0,0.000009,0.000017,0.000163,0.000153,0.001006,0.010363,0.117447,0.212400,0.070745,0.425923,1.523753,14.734218,5.397983,57.905356

In [235]:
numpy.savetxt("test.csv", a, delimiter=",")
df = pd.read_csv('test.csv', header=None)

In [310]:
digit = 12
timeCompare = [[0 for x in range(3)] for y in range(digit+1)] 
for i in range(digit+1):
    s1 = 'a'*i
    s2 = 'b'*i
    st = d.datetime.now()
    ans1 = editDistance(s1, s2, 0, 0)
    print(ans1, (d.datetime.now()-st).total_seconds())
    timeCompare[i][0] = (d.datetime.now()-st).total_seconds()
    dp = [[0 for x in range(len(s2)+1)] for y in range(len(s1)+1)] 
    st2 = d.datetime.now()
    ans2 = editDistanceTopDown(s1, s2, 0, 0, dp)
    timeCompare[i][1] = (d.datetime.now()-st2).total_seconds()
    st3 = d.datetime.now()
    ans3 = editDistanceBottomUp(s1, s2)
    timeCompare[i][2] = (d.datetime.now()-st3).total_seconds()
    if ans1 != ans2 or ans1 != ans3 or ans2 != ans3:
        raise Exception('BUG, ANS NOT EQUAL') 
print(timeCompare)

0 9e-06
1 5e-06
2 1.3e-05
3 5.3e-05
4 0.00026
5 0.001544
6 0.014549
7 0.062371
8 0.251363
9 1.440855
10 6.643509
11 41.037437
12 208.15042
[[0.000112, 2e-06, 7e-06], [6.7e-05, 6e-06, 8e-06], [4.1e-05, 1.1e-05, 2e-05], [9.3e-05, 2.2e-05, 1.7e-05], [0.000287, 3.4e-05, 2.3e-05], [0.001811, 9.1e-05, 5.9e-05], [0.014712, 0.000133, 7.9e-05], [0.062616, 0.000276, 0.0001], [0.251493, 0.000131, 6.7e-05], [1.441002, 0.000201, 0.000183], [6.643673, 0.000205, 9.9e-05], [41.037573, 0.000242, 0.000117], [208.150554, 0.000302, 0.000131]]

In [312]:
df = pd.DataFrame(
    timeCompare,
    columns=['recursive', 'top-down', 'bottom-up']
)
df.index+=1
df

     recursive  top-down  bottom-up
1     0.000112  0.000002   0.000007
2     0.000067  0.000006   0.000008
3     0.000041  0.000011   0.000020
4     0.000093  0.000022   0.000017
5     0.000287  0.000034   0.000023
6     0.001811  0.000091   0.000059
7     0.014712  0.000133   0.000079
8     0.062616  0.000276   0.000100
9     0.251493  0.000131   0.000067
10    1.441002  0.000201   0.000183
11    6.643673  0.000205   0.000099
12   41.037573  0.000242   0.000117
13  208.150554  0.000302   0.000131

In [259]:
# df.loc[:, 'recursive']
# list(df.columns.values)
df['recursive'].tolist()

[9e-06,
 9e-06,
 2.5e-05,
 0.000107,
 0.000455,
 0.001566,
 0.007853,
 0.063075,
 0.221547,
 1.598173,
 6.585327,
 41.087384,
 0.0,
 0.0,
 0.0]

In [313]:
digit = 12
timeCompare = [[0 for x in range(3)] for y in range(digit+1)] 
for i in range(digit+1):
    s1 = 'a'*i
    s2 = 'b'*i
    st = d.datetime.now()
    ans1 = editDistance(s1, s2, 0, 0)
    timeCompare[i][0] = (d.datetime.now()-st).total_seconds()
    dp = [[0 for x in range(len(s2)+1)] for y in range(len(s1)+1)] 
    st2 = d.datetime.now()
    ans2 = editDistanceTopDown(s1, s2, 0, 0, dp)
    timeCompare[i][1] = (d.datetime.now()-st2).total_seconds()
    st3 = d.datetime.now()
    ans3 = editDistanceBottomUp(s1, s2)
    timeCompare[i][2] = (d.datetime.now()-st3).total_seconds()
    if ans1 != ans2 or ans1 != ans3 or ans2 != ans3:
        raise Exception('BUG, ANS NOT EQUAL')

In [316]:
digit = 999
timeCompare2 = [[0 for x in range(2)] for y in range(digit+1)] 
for i in range(digit+1):
    s1 = 'a'*i
    s2 = 'b'*i
#     st = d.datetime.now()
#     ans1 = editDistance(s1, s2, 0, 0)
#     timeCompare[i][0] = (d.datetime.now()-st).total_seconds()
    dp = [[0 for x in range(len(s2)+1)] for y in range(len(s1)+1)] 
    st2 = d.datetime.now()
    ans2 = editDistanceTopDown(s1, s2, 0, 0, dp)
    timeCompare2[i][0] = (d.datetime.now()-st2).total_seconds()
    st3 = d.datetime.now()
    ans3 = editDistanceBottomUp(s1, s2)
    timeCompare2[i][1] = (d.datetime.now()-st3).total_seconds()
    if ans2 != ans3:
        raise Exception('BUG, ANS NOT EQUAL')

In [317]:
df = pd.DataFrame(
    timeCompare,
    columns=['recursive','top-down', 'bottom-up']
)
df.index+=1
df

df2 = pd.DataFrame(
    timeCompare2,
    columns=['top-down', 'bottom-up']
)
df2.index+=1
df2

      top-down  bottom-up
1     0.000049   0.000068
2     0.000021   0.000008
3     0.000013   0.000010
4     0.000020   0.000015
5     0.000061   0.000063
...        ...        ...
996   2.471692   0.909702
997   2.486695   0.909238
998   2.498281   0.918873
999   2.488875   0.919229
1000  2.496288   0.920657

[1000 rows x 2 columns]

In [318]:
from bokeh.io import output_file, show, output
from bokeh.layouts import gridplot
from bokeh.plotting import figure

output.reset_output(state=None)
# output_file("panning.html")

x = list(range(1, len(df['recursive'].tolist())+1))
y0 = df['recursive'].tolist()
y1 = df['top-down'].tolist()
y2 = df['bottom-up'].tolist()

x2 = list(range(1, len(df2['top-down'].tolist())+1))
y3 = df2['top-down'].tolist()
y4 = df2['bottom-up'].tolist()

# create a new plot
s1 = figure(plot_width=300, plot_height=250, title=None)
s1.line(x, y0, legend_label="recursive", line_color="blue")
s1.line(x, y1, legend_label="top-down", line_color="green")
s1.line(x, y2, legend_label="bottom-up", line_color="red")
s1.legend.location = "top_left"
# show(s1)
s1.circle(x, y0, size=3, color="blue", alpha=0.5)
s1.square(x, y1, size=3, color="green", alpha=0.5)
s1.triangle(x, y2, size=3, color="red", alpha=0.5)

s2 = figure(plot_width=300, plot_height=250, x_range=s1.x_range, title=None)
s2.line(x, y0, legend_label="recursive", line_color="blue")
s2.legend.location = "top_left"


s3 = figure(plot_width=300, plot_height=250, x_range=s1.x_range, title=None)
s3.line(x, y1, legend_label="top-down", line_color="green")
s3.line(x, y2, legend_label="bottom-up", line_color="red")
s3.legend.location = "top_left"

s4 = figure(plot_width=300, plot_height=250, title=None)
s4.line(x2, y3, legend_label="top-down", line_color="green")
s4.line(x2, y4, legend_label="bottom-up", line_color="red")
s4.legend.location = "top_left"



p = gridplot([[s1, s2, s3], [s4]])

# create a new plot and share both ranges
# s2 = figure(plot_width=250, plot_height=250, x_range=s1.x_range, title=None)
# s2.line(x, y1)
# s2.triangle(x, y1, size=10, color="firebrick", alpha=0.5)

# create a new plot and share only one range
# s3 = figure(plot_width=250, plot_height=250, x_range=s1.x_range, title=None)
# s3.line(x, y2)
# s3.square(x, y2, size=10, color="olive", alpha=0.5)

# p = gridplot([[s1, s2, s3]], toolbar_location=None)
# p.line(x, y2, legend="y=x")
# p.line(x, y0, legend="y=x^2", line_width=3)
# p.line(x, y1, legend="y=10^x", line_color="red")

# show the results
show(p)

In [319]:
def word2vec(word):
    from collections import Counter
    from math import sqrt

    # count the characters in word
    cw = Counter(word)
    # precomputes a set of the different characters
    sw = set(cw)
    # precomputes the "length" of the word vector
    lw = sqrt(sum(c*c for c in cw.values()))

    # return a tuple
    return cw, sw, lw

def cosdis(v1, v2):
    common = v1[1].intersection(v2[1])
    # by definition of cosine distance we have
    return sum(v1[0][ch]*v2[0][ch] for ch in common)/v1[2]/v2[2]

In [334]:
testa = 'ASDASDFEWEGEGEGE'
testb = 'AASFDSFDSASHEHEEGE'
va = word2vec(testa)
vb = word2vec(testb)
print(cosdis(va,vb))

0.8445997664172651

In [342]:
ex=['ATCG', 'CTCG', 'TTTT', 'GGGG']
for i in range(len(ex)):
    for j in range(i):
        print(i, j)
        va = word2vec(ex[i])
        vb = word2vec(ex[j])
        print(ex[i], ex[j],cosdis(va,vb))

1 0
CTCG ATCG 0.8164965809277261
2 0
TTTT ATCG 0.5
2 1
TTTT CTCG 0.4082482904638631
3 0
GGGG ATCG 0.5
3 1
GGGG CTCG 0.4082482904638631
3 2
GGGG TTTT 0.0